INSERT INTO genre (name) VALUES('Action and adventure');
INSERT INTO genre (name) VALUES('Art/architecture');
INSERT INTO genre (name) VALUES('Alternate history');
INSERT INTO genre (name) VALUES('Autobiography');
INSERT INTO genre (name) VALUES('Anthology');
INSERT INTO genre (name) VALUES('Biography');
INSERT INTO genre (name) VALUES('Chick lit');
INSERT INTO genre (name) VALUES('Business/economics');
INSERT INTO genre (name) VALUES('Childrens');
INSERT INTO genre (name) VALUES('Crafts/hobbies');
INSERT INTO genre (name) VALUES('Classic');
INSERT INTO genre (name) VALUES('Cookbook');
INSERT INTO genre (name) VALUES('Comic book');
INSERT INTO genre (name) VALUES('Diary');
INSERT INTO genre (name) VALUES('Coming-of-age');
INSERT INTO genre (name) VALUES('Dictionary');
INSERT INTO genre (name) VALUES('Crime');
INSERT INTO genre (name) VALUES('Encyclopedia');
INSERT INTO genre (name) VALUES('Drama');
INSERT INTO genre (name) VALUES('Guide');
INSERT INTO genre (name) VALUES('Fairytale');
INSERT INTO genre (name) VALUES('Health/fitness');
INSERT INTO genre (name) VALUES('Fantasy');
INSERT INTO genre (name) VALUES('History');
INSERT INTO genre (name) VALUES('Graphic novel');
INSERT INTO genre (name) VALUES('Home and garden');
INSERT INTO genre (name) VALUES('Historical fiction');
INSERT INTO genre (name) VALUES('Humor');
INSERT INTO genre (name) VALUES('Horror');
INSERT INTO genre (name) VALUES('Journal');
INSERT INTO genre (name) VALUES('Mystery');
INSERT INTO genre (name) VALUES('Math');
INSERT INTO genre (name) VALUES('Paranormal romance');
INSERT INTO genre (name) VALUES('Memoir');
INSERT INTO genre (name) VALUES('Picture book');
INSERT INTO genre (name) VALUES('Philosophy');
INSERT INTO genre (name) VALUES('Poetry');
INSERT INTO genre (name) VALUES('Prayer');
INSERT INTO genre (name) VALUES('Political thriller');
INSERT INTO genre (name) VALUES('Romance');
INSERT INTO genre (name) VALUES('Textbook');
INSERT INTO genre (name) VALUES('Satire');
INSERT INTO genre (name) VALUES('Science fiction');
INSERT INTO genre (name) VALUES('Review');
INSERT INTO genre (name) VALUES('Short story');
INSERT INTO genre (name) VALUES('Science');
INSERT INTO genre (name) VALUES('Suspense');
INSERT INTO genre (name) VALUES('Self help');
INSERT INTO genre (name) VALUES('Thriller');
INSERT INTO genre (name) VALUES('Sports and leisure');
INSERT INTO genre (name) VALUES('Western');
INSERT INTO genre (name) VALUES('Travel');
INSERT INTO genre (name) VALUES('Young adult');
INSERT INTO genre (name) VALUES('True crime');


INSERT INTO publisher (name, parent_company, country, revenue) VALUES ('Pearson','Pearson PLC','U.K.','$6,070');
INSERT INTO publisher (name, parent_company, country, revenue) VALUES ('RELX Group','Reed Elsevier PLC & Reed Elsevier NV','U.K./U.S./Netherlands','$5,609');
INSERT INTO publisher (name, parent_company, country, revenue) VALUES ('Thomson Reuters','The Woodbridge Company Ltd.','Canada','$4,941');
INSERT INTO publisher (name, parent_company, country, revenue) VALUES ('Bertelsmann','Bertelsmann AG','Germany','$4,240');
INSERT INTO publisher (name, parent_company, country, revenue) VALUES ('Wolters Kluwer','Wolters Kluwer','Netherlands','$3,994');
INSERT INTO publisher (name, parent_company, country, revenue) VALUES ('Hachette Livre','Lagardère','France','$2,735');
INSERT INTO publisher (name, parent_company, country, revenue) VALUES ('Grupo Planeta','Grupo Planeta','Spain','$1,974');
INSERT INTO publisher (name, parent_company, country, revenue) VALUES ('Springer Nature','Springer Nature','Germany','$1,956');
INSERT INTO publisher (name, parent_company, country, revenue) VALUES ('Scholastic','Scholastic','U.S.','$1,742');
INSERT INTO publisher (name, parent_company, country, revenue) VALUES ('McGraw-Hill Education','Apollo Global Management LLC','U.S.','$1,719');
INSERT INTO publisher (name, parent_company, country, revenue) VALUES ('Wiley','Wiley','U.S.','$1,719');
INSERT INTO publisher (name, parent_company, country, revenue) VALUES ('HarperCollins','News Corp','U.S.','$1,636');
INSERT INTO publisher (name, parent_company, country, revenue) VALUES ('Houghton Mifflin Harcourt','Apax and Omers Capital Partners','U.S./Canada','$1,461');
INSERT INTO publisher (name, parent_company, country, revenue) VALUES ('Holtzbrinck','Houghton Mifflin Harcourt Co.','U.S./Cayman Islands','$1,408');
INSERT INTO publisher (name, parent_company, country, revenue) VALUES ('Informa','Verlagsgruppe Georg von Holtzbrinck','Germany','$1,403');
INSERT INTO publisher (name, parent_company, country, revenue) VALUES ('Oxford University Press','Informa PLC','U.K.','$1,229');
INSERT INTO publisher (name, parent_company, country, revenue) VALUES ('Kodansha','Oxford University','U.K.','$1,139');
INSERT INTO publisher (name, parent_company, country, revenue) VALUES ('Shueisha','Kodansha Ltd.','Japan','$1,045');
INSERT INTO publisher (name, parent_company, country, revenue) VALUES ('Kadokawa Publishing','Hitotsubashi Group','Japan','$1,041');
INSERT INTO publisher (name, parent_company, country, revenue) VALUES ('Cengage Learning Holdings II','Kadokawa Holdings Inc.','Japan','$998');